services:
  app:
    build: .
    container_name: yt_knowledge_base
    ports:
      - "8000:8000"
    environment:
      - APP_ENV=production
      - HOST=0.0.0.0
      - PORT=8000
    volumes:
      - ./data:/app/data
      - ./vector_db:/app/vector_db
      - ./logs:/app/logs
      - hf_cache:/app/.cache/huggingface
      - st_cache:/app/.cache/sentence-transformers
    restart: unless-stopped


volumes:
  hf_cache:
  st_cache: